### PR TITLE
Minor: Udpate Windows batch script

### PR DESCRIPTION
**Pull request by regisd**
Use `%*` for remaining args, instead of `%1` `%2` `%3` ... `%9`
(which might me a couple)

### CODE REVIEW

**Comment by regisd** [comment]
I don't have a Windows machine to test the change, though.

**Comment by lsf37** [comment]
I have this commit on the release branch and I have access to a Windows machine. Should be able to test it tomorrow.

**Comment by lsf37** [comment]
This seems to be working (I tested it in isolation on a windows box). Happy enough to include it in master for now, I'll do a bigger test when I have the full release package working.

**Comment by regisd** [comment]
I'm not using Windows. Up to you if you want to include in 1.7.0 or wait for a subsequent release.

**Pull request merged**
