### PR TITLE
Fix FindBugs issues

### PR DESCRIPTION
**Pull request by kinow**
Found a few Maps being iterated twice while preparing another pull request. Then triggered a `mvn clean findbugs:findbugs findbugs:gui`, and fixed a few ones. No regressions found running `./run-test`

### CODE REVIEW

**Comment by regisd** [comment]
Thanks for cleaning up the code. LGTM. Before I pull, I'll have a look why travis fails — I guess Travis changed something in the environment.

**Comment by regisd** [comment]
Closing and reoping pull request, so that Travis is triggered with the travis.yml changed in c51377cdb3ad27922268130ac8c633da3fe640dd

**Comment by regisd** [comment]
Travis, please build again.

**Comment by kinow** [comment]
Thanks!!!

**Comment by regisd** [comment]
Arg! no, I did a mistake with git and managed to lose this pull request. I'm glad you haven't deleted your branch yet.
This pull request is replaced by #224

**Pull request merged**
