### PR TITLE
Bump to version 1.7.1

### PR DESCRIPTION
**Pull request by lsf37**
Contains two tweak commits to fix up release and post release script for next time

### CODE REVIEW

**Comment by lsf37** [comment]
@regisd the `aggregated-java-sources` deployment seems not to have been triggered by the merge of 1.7.0 to master. Not sure if you prefer this merged first or holding off until that is resolved.

**Comment by regisd** [comment]
Yes, I think I decide to trigger the aggregated-java-sources on a branch named "release". The reason is that you probably built the release from jflex-1.7.0 branch ; and I realised that there could be differences with master.
So, in theory, the only thing to do is
```
git co -b release
git push
```
and then the release branch can be deleted too.

**Comment by lsf37** [comment]
Ok, will try that. Otherwise the release is now out and seems to have gone well. I'll let you have a look before announcing it!

**Comment by regisd** [comment]
Ah, my mistake. This change was in PR #332

**Comment by regisd** [comment]
Right. So, I think the Travis config is now correct, and https://travis-ci.org/jflex-de/jflex/builds/431386863 should update the maven-site.
The sources will be updated on evety commit on master, and need to be tagged manually.

**Comment by lsf37** [comment]
There usually are bugs :-) We have a few small things on the 1.7.1 milestone. If they become too big for a minor release we can still bump it up to 1.8.0 fairly easily.

**Comment by lsf37** [comment]
I’ll merge this one now so the repo is back in dev mode. If you feel strongly about going to 1.8.0 directly I’m fine with bumping it up again.

**Pull request merged**
