### PR TITLE
Restore building docs in Travis

### LINKED ISSUE #571: [master] docs doesn't build on Travis
```
! Undefined control sequence.
l.27 \tightlist
```

### PR DESCRIPTION
**Pull request by regisd**
fixes #571

### CODE REVIEW

**Comment by lsf37** [comment]
It looks like the `\tightlist` is just stuff newer pandoc versions generate. Should hopefully work now.

**Comment by lsf37** [comment]
Travis is getting stuck on installing dependencies. We can probably reduce them slightly.

**Comment by lsf37** [comment]
> Travis is getting stuck on installing dependencies. We can probably reduce them slightly.

Or not. I can't actually see much that we can leave out.

**Comment by lsf37** [comment]
@regisd The docs now do work on Travis after all, even though the tex-live installation takes quite a while. I'm happy to merge it if your are.

**Comment by regisd** [comment]
I remember adding `\tightlist` for the bazel build (in commit 20eac47577a47c4d804f2c0185cd44f30a787259). I don't understand what as change on the Travis side. But if it's green, let's submit.

**Pull request merged**
