### PR TITLE
Add google error-prone in compile step.

### PR DESCRIPTION
**Pull request by regisd**
Note that FallThrough violations have been reduced to warnings.

issue #222

### CODE REVIEW

**Comment by lsf37** [comment]
The test seems to have failed on something strange:
`The command "mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V" failed and exited with 1`

Any idea where that is from?

**Comment by regisd** [comment]
That's from:
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project jflex-unicode-maven-plugin: Execution default-compile of goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-compiler-plugin:3.3:compile: java.lang.UnsupportedClassVersionError: javax/tools/DiagnosticListener : Unsupported major.minor version 52.0

The error-prone plugin is compiled with Java 8, and Travis uses openjdk7. See #225

**Comment by lsf37** [comment]
Right, let me ping Travis again to see if it all works on jdk8. Could we run the plugin conditionally when jdk8 is available?

**Comment by regisd** [comment]
So, indeed

- 155.1 on openjdk7 fails
- 155.2 on openjdk8 passes

**Pull request merged**
