### PR TITLE
Restore ant test for examples/simple

### LINKED ISSUE #376: ant build doesn't support jUnit @Test annotation
A simple test class using junit 4 `@Test` annotations passes in the Maven build, but fails with ant build

>     [junit] 	Caused an ERROR
>     [junit] org/hamcrest/SelfDescribing
>     [junit] java.lang.NoClassDefFoundError: org/hamcrest/SelfDescribing
>     [junit] 	at java.lang.ClassLoader.defineClass1(Native Method)
>     [junit] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
>     [junit] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
>     [junit] 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
>     [junit] 	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
>     [junit] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
>     [junit] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
>     [junit] 	at java.security.AccessController.doPrivileged(Native Method)
>     [junit] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
>     [junit] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
>     [junit] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
>     [junit] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
>     [junit] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
>     [junit] Caused by: java.lang.ClassNotFoundException: org.hamcrest.SelfDescribing
>     [junit] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:359)
>     [junit] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
>     [junit] 	at java.security.AccessController.doPrivileged(Native Method)
>     [junit] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
>     [junit] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
>     [junit] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
>     [junit] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)

https://travis-ci.org/jflex-de/jflex/jobs/432894291

### PR DESCRIPTION
**Pull request by regisd**
* Modernize example with junit annotations.
* Load dependencies with ivy. 
  TODO: Do the same on the JFlex core build.xml #376
* Restore ant test. 
* Update documentation

### CODE REVIEW

**Comment by lsf37** [comment]
It still seems to be catching the wrong java_cup runtime somehow.

**Comment by regisd** [comment]
Yes, this PR is blocked by #384

**Comment by regisd** [comment]
I don't understand. This is changing `examples/simple` and Travis suddenly fails on `cup-interpreter`.

**Comment by regisd** [comment]
Blocked by circular dependencies
circular dependency found: com.google.truth#truth;0.36->com.google.testing.compile#compile-testing;0.12->com.google.truth#truth;0.35
https://stackoverflow.com/questions/52783476/circular-dependencies-in-apache-ivy

**Comment by sarowe** [comment]
You could add transitive=“false” to the truth dep and then add all its deps explicitly

**Comment by regisd** [comment]
Actually, I misread the logs. Beside this warning, there is an error

> [ivy:cachepath] 		::          UNRESOLVED DEPENDENCIES         ::
> [ivy:cachepath] 		::::::::::::::::::::::::::::::::::::::::::::::
> [ivy:cachepath] 		:: com.google.gwt#gwt-user;2.8.0: com.google.gwt#gwt;2.8.0->org.sonatype.oss#oss-parent;4

**Comment by regisd** [comment]
https://issues.apache.org/jira/browse/IVY-1588

**Pull request merged**
