### PR TITLE
Make `yychar` long

### LINKED ISSUE #536: Lexer has negative yychar when processing files larger than 2 GiB
The `yychar` variable that holds file offset is `int`, therefore limiting the length of files to 2 GiB - 1. We bumped into this in https://github.com/oracle/opengrok/issues/2560

### PR DESCRIPTION
**Pull request by regisd**
Fix #536.

When the input is larger than 2GB, the scanner internal state for the number of read characters (aka `zzchar`) is negative. This obviously doesn't make sense.

The test added in #603 reproduces the problem and throws an exception, when the `zzchar` is negative.

The problem is caused by `yychar` being an `int`, hence subject to overflow.

Fix #558 by making `yychar` long. This is similar to #558 by @sarowe with a lighter approach for testing.

Note that some problems remain:
- `yyline` and `yycolumn` are still  integers.
- if the match section is larger than 2GB, then
  - you will likely have an OutOfMemory error
  - even if you have enough heap size, `zzRefill()` will throw a `NegativeArraySizeException` like this
    > java.lang.NegativeArraySizeException
    > 	at jflex.testcase.large_input.LargeInputScanner.zzRefill(LargeInputScanner.java:288)
    > 	at jflex.testcase.large_input.LargeInputScanner.yylex(LargeInputScanner.java:601)
    > 	at jflex.testcase.large_input.LargeInputTest.consumeLargeInput(LargeInputTest.java:22)
    > 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

### CODE REVIEW

**Comment by regisd** [comment]
Thanks for the positive feedback, Gerwin.

My opinion is that:

- It's OK to do API breaking changes, particularly because there was none in the last year (with a slow release cycle, changes can/will be more brutal), and very few in the  last decade.
- There is no need to announce much in advance. Users have to read the changelog and update their code when they upgrade the dep.

That being said, I think 1.8 has accumulated enough changes to be released.

**Comment by lsf37** [comment]
Yes, I meant making it prominent in the release announcement (just because API breaking changes are rare for JFlex), I agree that we don't want to announce it before.

**Comment by lsf37** [comment]
Forgot to say: I agree that 1.8 is getting there. Still labouring under the illusion that I'll manage to pull in the char class macros (#216) into 1.8. Recently made some progress on that, but there is still some way to go.

**Comment by regisd** [comment]
Follow-up comment for those who hit this breaking change. There are two options to fix it:
- either adapt the consuming code and use `long` as well.
- or there is a guarantee that `yychar` is neither larger or equal to 2^31 in which case it's possible to wrap `yychar` with [Math.toExactInt()](https://docs.oracle.com/javase/8/docs/api/java/lang/Math.html#toIntExact-long-)

**Pull request merged**
